### ISSUE TITLE
Treksy: Make logo and favicon

### ISSUE THREAD

**Issue by Swatilekha-Roy** [prathimacode-hub/Treksy#10]
Feel free to be creative! And please take care of the following criteria:
- upload two versions of both logo and favicon- one with white bg and another with transparent bg.
- name the images semantically (e.g.: logo_bg, logo_wtbg, etc.)
Try and get your designs approved before making final pr.

How to get designs approved?
- Comment your designs on this thread and wait for one of the mentors to get back to you.
- Once your designs are approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/Treksy/blob/main/CONTRIBUTING.md) at least once before contributing code.

**Comment by Shikha785** [comment]
I want to work on this issue under JWOC .

**Comment by Swatilekha-Roy** [comment]
All the best, @Shikha785! Just assigned you.

**Comment by Swatilekha-Roy** [comment]
What is your status update, @Shikha785?

**Comment by prathimacode-hub** [comment]
@Shikha785, you should give your status and update the reason instead of removing your assignment by own without informing

**Comment by Shikha785** [comment]
I am sorry that I acted without informing.

**Comment by khushbubijawat** [comment]
is this issue assigned now?

**Comment by prathimacode-hub** [comment]
If you don't want to work let me know so that I can assign to next person on queue @Shikha785 

@khushbubijawat, let's await a decision from @Shikha785

**Comment by Shikha785** [comment]
You may assign it to the @khushbubijawat  .

**Comment by prathimacode-hub** [comment]
Issue assigned to @Shikha785

**Comment by Shikha785** [comment]
![logo](https://user-images.githubusercontent.com/92089976/152403071-1decd13f-3c7f-4172-8c35-3cb967ea7a82.png)
![favicon_bg](https://user-images.githubusercontent.com/92089976/152403125-1a44afb4-6273-4036-a924-68187c08745b.png)
![logo (2)](https://user-images.githubusercontent.com/92089976/152403188-179acb9f-98eb-41bb-b4a5-08235e3775b5.PNG)
![favicon_wtbg](https://user-images.githubusercontent.com/92089976/152404330-dd70416f-e477-4458-a4fe-aebd3af821d7.png)
Please check the attachments.

**Comment by Shikha785** [comment]
![favicon](https://user-images.githubusercontent.com/92089976/152531533-80e52348-007d-42c5-b52e-542c2a118921.png)
![favicon_bg](https://user-images.githubusercontent.com/92089976/152531562-d3f381f7-3c24-4cba-ada9-205f20eabe98.png)
![favicon_wtbg](https://user-images.githubusercontent.com/92089976/152531587-2bd71c0e-c7b1-46a5-8219-d1303ebc8534.png)
![logo col](https://user-images.githubusercontent.com/92089976/152532897-6291e272-dc1b-497a-b875-de184653d85e.PNG)
![logo](https://user-images.githubusercontent.com/92089976/152532918-5b5f9abc-0a9d-420d-8990-1ef2f876eebd.png)
![logo_bg](https://user-images.githubusercontent.com/92089976/152535896-a6ea4848-c386-4f8f-b2e2-3f85730057a5.png)
Added different favicons and logos.

**Comment by prathimacode-hub** [comment]
We need logo and favicon both in white and transparent background. And all should be similar. Send the images in this format to review. And name it while adding the image so that it gives clear representation. @Shikha785

**Comment by ronitblenz** [comment]
I would like to work on this issue ma'am, I have prior experience in logo and favicon in your other project.

Thanks

**Comment by binayshaw7777** [comment]
I want to work on this issue under JWOC.

**Comment by prathimacode-hub** [comment]
@binayshaw7777 @ronitblenz, I will let you know once i get update from previously assigned mentee

**Comment by binayshaw7777** [comment]
> @binayshaw7777 @ronitblenz, I will let you know once i get update from previously assigned mentee

Ok sure, but we've hardly 3 days left, so it'll be great if I get the green signal to design it asap. I mean JWOC will end soon.

**Comment by ronitblenz** [comment]
@prathimacode-hub You can assign @binayshaw7777 , I am caught up with gssoc PA works... 😊🤞

**Comment by KushalGhosh9899** [comment]
I want to work on this issue under JWOC if anyone is not working on it

**Comment by prathimacode-hub** [comment]
Ok, you can proceed to work on this issue. @KushalGhosh9899

**Comment by binayshaw7777** [comment]
> Ok, you can proceed to work on this issue. @KushalGhosh9899

I already asked to get assigned and there was no reply. Can you please be check old comments? Is this first cum first serve?

**Comment by KushalGhosh9899** [comment]
Are buddy @binayshaw7777 why are you getting so rude yr. Open source is all about collaborating and solving the issue, open source is not about competition. I think you are taking open source in the wrong way. Anyways if you want you can take up this issue I have no problem.

**Comment by binayshaw7777** [comment]
> Are buddy @binayshaw7777 why are you getting so rude yr. Open source is all about collaborating and solving the issue, open source is not about competition. I think you are taking open source in the wrong way. Anyways if you want you can take up this issue I have no problem.

I'm not getting rude bud, its not the first time this happened with me. This drives me craze. You can work on it, np. It's not about contribution, it feels biased sometimes Ike.

**Comment by prathimacode-hub** [comment]
Ok, @binayshaw7777 issue is assigned to you. I haven't done any bias here. I asked you and ronit both to update but last msg which you had given hasn't shown up at my end. Its on first come first serve only. 

Open source is all about collaboration and competition. Sorry, if that made you offended. 

@KushalGhosh9899, you can come up with some other issue.

**Comment by binayshaw7777** [comment]
> Ok, @binayshaw7777 issue is assigned to you. I haven't done any bias here. I asked you and ronit both to update but last msg which you had given hasn't shown up at my end. Its on first come first serve only.
> 
> Open source is all about collaboration and competition. Sorry, if that made you offended.
> 
> @KushalGhosh9899, you can come up with some other issue.

Ma'am I said it feels like.. I'm sorry it seemed rude. I and Ronit already commented two weeks ago, after your response I already replied, so I was expecting a green signal, that's all.

**Comment by binayshaw7777** [comment]
@prathimacode-hub  you check the status here: https://www.figma.com/file/lEl3nsUAEWYXtzlduAE8uw/Tresky?node-id=0%3A1

**Comment by prathimacode-hub** [comment]
It looks like maps pointer and it doesn't resemble what this site is about. @binayshaw7777

**Comment by binayshaw7777** [comment]
> It looks like maps pointer and it doesn't resemble what this site is about. @binayshaw7777

I have some designs in my mind but can you please let me know what of logo are you expecting. That way I can figure out the what to do. Else I can prepare 4-5 more logo. Then you can choose.

**Comment by prathimacode-hub** [comment]
Ok, something that depicts responsible travel and offbeat explorations. @binayshaw7777
