### ISSUE TITLE
Treksy : Create a Footer Section for the Home Page

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Treksy#11]
Hey JWOC participants, good to see you.

This issue's goal is to create a footer section of home page which also includes Navigation bar of travel webapp

If you like to work on this issue, follow the contributing guidelines provided and have a good read of them along with README file

**Comment by VaishnaviNigam25** [comment]
I would like to know more about this in detail & work under JWOC

**Comment by Swatilekha-Roy** [comment]
All the best, @VaishnaviNigam25! Just assigned you.
Feel free to use the following reference for making the footer and feel free to be creative:
[Trip Advisor](https://www.tripadvisor.in/)
