### ISSUE TITLE
Treksy: Make the folder and file structure

### ISSUE THREAD

**Issue by Swatilekha-Roy** [prathimacode-hub/Treksy#13]
If you are not aware about how to semantically make a folder or file structure for the web, you may refer to the following links for reference:

- [Appcropolis](https://appcropolis.com/blog/web-technology/organize-html-css-javascript-files/)
- [Pixinvent](https://pixinvent.com/demo/vuexy-html-bootstrap-admin-template/documentation/documentation-folder-structure.html)
- [Medium](https://medium.com/@nmayurashok/file-and-folder-structure-for-web-development-8c5c83810a5)

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/Treksy/blob/main/CONTRIBUTING.md) at least once before contributing code to Tresky.

**Comment by prathimacode-hub** [comment]
Issue assigned to @unnikrishnan2002
