### ISSUE TITLE
Treksy: Make a "Blogs" Page with Blog Cards

### ISSUE THREAD

**Issue by Swatilekha-Roy** [prathimacode-hub/Treksy#22]
Build a Treksy Blog Page with multiple cards that have some text block and accompanying images. Follow the following as a part of your checklist.
- Make sure that the images you use are uncopyrighted (Some sources are [Pexels](https://www.pexels.com/), [Pixabay](https://pixabay.com/), [Unsplash](https://unsplash.com/images) ).
- Use Treksy relevant text and images (feel free to use your creativity)
- Make sure that Blog is linked in all correct places (navbar, footer, etc.)

Feel free to use the below link as a reference:
[Blog Top 50](https://detailed.com/50/)

**Comment by Mainakroy050** [comment]
I want to work on this issue under JWOC

**Comment by Swatilekha-Roy** [comment]
Just assigned you, @Mainakroy050! All the best.
