### ISSUE TITLE
Treksy: Add a Map Popup for Footer "Site Map"

### ISSUE THREAD

**Issue by Swatilekha-Roy** [prathimacode-hub/Treksy#23]
- Feel free to use any dummy address location as Treksy fictional location. You may use [Randommer](https://randommer.io/random-address) for the same.
- Pinpoint this address on a map popup in the footer.
- Feel free to use any existing map services (some examples are Google Maps, Azure Maps, Open Street Map, etc.)

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/Treksy/blob/main/CONTRIBUTING.md) at least once before contributing code to Treksy.

**Comment by unnikrishnan2002** [comment]
> * Feel free to use any dummy address location as Treksy fictional location. You may use [Randommer](https://randommer.io/random-address) for the same.
> * Pinpoint this address on a map popup in the footer.
> * Feel free to use any existing map services (some examples are Google Maps, Azure Maps, Open Street Map, etc.)
> 
> Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/Treksy/blob/main/CONTRIBUTING.md) at least once before contributing code to Treksy.

I would like to try this under JWOC

**Comment by prathimacode-hub** [comment]
Sure, you can proceed @unnikrishnan2002
