### ISSUE TITLE
Treksy: Tie up the existing site UI-s and make styling similar

### ISSUE THREAD

**Issue by Swatilekha-Roy** [prathimacode-hub/Treksy#24]
The existing pages: index.html, about.html, contact.html look awesome independently but could one of our awesome creative mentees make sure that it looks like a consolidated app? 😉 
Extra brownies for creativity and travel theme! Feel free to make changes according to your discretion.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/Treksy/blob/main/CONTRIBUTING.md) at least once before contributing code to Tresky.

**Comment by Tess-Vanta** [comment]
I want to work on this issue under JWOC

**Comment by Anosh21** [comment]
I would like to contribute in this issue under jwoc

**Comment by ronitblenz** [comment]
Hello, 
I have recently merged 3 PRs in open source and did 5+ hackathons,
Will you kindly add as an assignee
And Could you please explain what did you mean by consolidated app?

Thanks and Regards

**Comment by Swatilekha-Roy** [comment]
Assigned to you, @Anosh21! All the best. 🥳 

You're in queue, @ronitblenz.

**Comment by Anosh21** [comment]
Thanks @Swatilekha-Roy

**Comment by ronitblenz** [comment]
> Assigned to you, @Anosh21! All the best. 🥳
> 
> You're in queue, @ronitblenz. Also to answer your question, by consolidated app, I am referring to a travel app that looks uniform in terms of its theme across all pages which looks different right now as different people have made different pages.

Got your point. 😊

**Comment by Anosh21** [comment]
Hey @Swatilekha-Roy Check my PR .

**Comment by prathimacode-hub** [comment]
Kindly work on the changes addressed to your PR @Anosh21
