### ISSUE TITLE
Treksy: Add travel themed carousel to homepage

### ISSUE THREAD

**Issue by Swatilekha-Roy** [prathimacode-hub/Treksy#25]
Add a travel-themed carousel to index.html. Make sure you use uncopyrighted images (links pinned on Discord channel). Use 4-5 slides in the carousel, heroing different Treksy features. Feel free to use below reference:

[Texhnext](https://technext.github.io/montana/index.html)

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/Treksy/blob/main/CONTRIBUTING.md) at least once before contributing code to Tresky.

**Comment by unnikrishnan2002** [comment]
I would like to work on this as well for JWOC

**Comment by prathimacode-hub** [comment]
I think you got assigned to another issue too. Will you be able to complete both on time? @unnikrishnan2002

**Comment by unnikrishnan2002** [comment]
> I think you got assigned to another issue too. Will you be able to complete both on time? @unnikrishnan2002

Yes I can complete

**Comment by prathimacode-hub** [comment]
Ok, glad to see your enthusiasm. Issue assigned to @unnikrishnan2002
