### ISSUE TITLE
Treksy : Create About Section for Website

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Treksy#3]
Hey JWOC participants, good to see you.

This issue's goal is to create an external layout of about page of the website.

If you like to work on this issue, follow the contributing guidelines provided and have a good read of them along with README file

**Comment by shinigamirex888** [comment]
@prathimacode-hub  Hey I want to work on this issue. Can you please assign it to me.

**Comment by prathimacode-hub** [comment]
Are you a JWoC participant?

**Comment by shinigamirex888** [comment]
> Are you a JWoC participant?

Yes

**Comment by prathimacode-hub** [comment]
@shinigamirex888 Issues are assigned only from Feb 1st onward according to the guideline given by JWoC on first come first serve basis. To get more details on it, check through the project channel on JWoC discord server. Basic details a mentee needs to know has been provided there.

**Comment by Shruti025** [comment]
I want to work on this issue under JWOC

**Comment by prathimacode-hub** [comment]
Issue assigned to @Shruti025

**Comment by combatantash** [comment]
I want to work on this issue under JWOC

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by Swatilekha-Roy** [comment]
Hello @Shruti025 please feel free to add an "About Tresky" section (suggested tech stack: HTML, CSS, JSS, Bootstrap but feel free to use whatever you are comfy with) on the website with relevant text and also a relevant image (feel free to use any uncopyrighted images or graphics):
Here is a sample resource of "ABOUT US" for you to reference:
[](https://www.tripodeal.com/travel/about-us/)

Feel free to be creative! All the best. 😸

**Comment by Shruti025** [comment]
thank you @Swatilekha-Roy :)
