### ISSUE TITLE
Treksy [React-Version] : Create a Navbar and carousel for the react version of the website

### ISSUE THREAD

**Issue by unnikrishnan2002** [prathimacode-hub/Treksy#34]
@prathimacode-hub @Swatilekha-Roy  I would like to work on this issue under JWOC, making a navbar and carousel for the react app. I will make sure that the UI look a little different from current version of the app .

**Comment by prathimacode-hub** [comment]
That's awesome. I'm sure you will rock. Issue assigned to @unnikrishnan2002

**Comment by unnikrishnan2002** [comment]
> That's awesome. I'm sure you will rock. Issue assigned to @unnikrishnan2002

Can you put the medium tag
