### ISSUE TITLE
Treksy: Add Homepage's Navbar and Footer to all existing pages

### ISSUE THREAD

**Issue by Swatilekha-Roy** [prathimacode-hub/Treksy#35]
- [ ] Add the existing navbar and footer to all existing pages: HOME, ABOUT, BLOGS, CONTACT US, BOOKING. 
- [ ] Ensure that all the pages' navbar have correct paths set.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/Treksy/blob/main/CONTRIBUTING.md) at least once before contributing code to Tresky.

**Comment by unnikrishnan2002** [comment]
@Swatilekha-Roy I believe that this work is included in  #24 . What are your thoughts ?

**Comment by ishitaac** [comment]
want to work this issue under jwoc

**Comment by tanya-gupta25** [comment]
I want to work this issue under JWOC

**Comment by sayan404** [comment]
I want to work in this issue under JWOC .

**Comment by Priiyaa** [comment]
I would like to work on this under JWOC

**Comment by Swatilekha-Roy** [comment]
Please go ahead, @ishitaac! Assigned to you.

To answer your question, setting the paths and adding the navbar and footer won't be part of issue #24. Thanks for the heads up btw! 😄

**Comment by prathimacode-hub** [comment]
Update please? @ishitaac

**Comment by prathimacode-hub** [comment]
You're on queue as this issue level is changed. @ronitblenz

**Comment by ishitaac** [comment]
> Update please? @ishitaac

Yes will push the code by tonight, had a talk to you regarding the same on discord
