### ISSUE TITLE
Treksy: Add animations across all pages as suitable

### ISSUE THREAD

**Issue by Swatilekha-Roy** [prathimacode-hub/Treksy#36]
One disclaimer here: please don't overdo CSS animations as those may hamper accessibility. Stick to your guns and add as much as is presentable and soothing to look at, not too much! 

Feel free to use any existing animation libraries or feel free to write your own CSS code. 
Suggested Animation library: [WOW.js](https://wowjs.uk/)

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/Treksy/blob/main/CONTRIBUTING.md) at least once before contributing code to Tresky.

**Comment by ashutoshnautiyal7** [comment]
I would like to work on this under JWOC.

**Comment by prathimacode-hub** [comment]
Issue assigned to @ashutoshnautiyal7
