### ISSUE TITLE
Treksy: Add contact.html back-end

### ISSUE THREAD

**Issue by Swatilekha-Roy** [prathimacode-hub/Treksy#37]
Please make a back-end for the contact.html so that anyone who submits the form gets the data delivered to a relevant email address. You may use this existing API:
[FormSubmit](https://formsubmit.co/)
Please make sure that the information gets sent to [kadariprathima4@gmail.com](kadariprathima4@gmail.com)

Please use a honeycomb captcha for Form Submit rather than its existing recaptcha service. The above link should provide all necessary references.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/Treksy/blob/main/CONTRIBUTING.md) at least once before contributing code to Tresky.

**Comment by abhiimali** [comment]
helllo , 

i am working on similar kind of feature in my personal project .. if any one not assigned here will try to do it also . 

is is okay ?

**Comment by Anirban-1490** [comment]
form submission using only the API ? or a real backend needed ?

**Comment by harshit-070** [comment]
i want to work on this under JWOC

**Comment by Swatilekha-Roy** [comment]
Hi @Anirban-1490 form submission only using API is sufficient for now. Please just make sure that you are following all the criteria for the issue. I am assuming you asked the question as you're interested in the issue, so am assigning you. All the best!
@harshit-070 you're in queue.

**Comment by Anirban-1490** [comment]
@Swatilekha-Roy I have added the desired mail id but the hCaptcha needs an account with 2 keys to work. I am using my own account for testing and the keys. So what's next ?

**Comment by prathimacode-hub** [comment]
What's the key you're asking. can you elaborate? @Anirban-1490

**Comment by prathimacode-hub** [comment]
Yes absolutely. Ok for time being, you can add it up with your account key. Later, we can replace it once account if created
@Anirban-1490

**Comment by Anirban-1490** [comment]
@prathimacode-hub Also one thing should i just push the keys like that in here ?, it will be public which is not a good thing but even using a .env file that keys will be still viewable in inspection .

**Comment by prathimacode-hub** [comment]
You can use .gitnore to block the keys and sensitive information. @Anirban-1490
