### ISSUE TITLE
Treksy : Create Contact Section for Website

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Treksy#4]
Hey JWOC participants, good to see you.

This issue's goal is to create an external layout of contact page of the website.

If you like to work on this issue, follow the contributing guidelines provided and have a good read of them along with README file

**Comment by Riddhi9570** [comment]
@prathimacode-hub Hey! I'm interested to work on this issue. Please assign it to me.

**Comment by prathimacode-hub** [comment]
Are you a JWoC participant? @Riddhi9570

**Comment by prathimacode-hub** [comment]
@shinigamirex888 If so, Issues are assigned only from Feb 1st onward according to the guideline given by JWoC on first come first serve basis. To get more details on it, check through the project channel on JWoC discord server. Basic details a mentee needs to know has been provided there.

**Comment by Riddhi9570** [comment]
@prathimacode-hub Yes, I'm a JWOC participant. Thanks for the information. But please do let me know if there are particular fields required to be added in the contact section or I may do it on my own by adding few basic contact details.

**Comment by prathimacode-hub** [comment]
For now, we can do it in a format just for template and add dummy details. But don't initiate any task now. Express your interest on Feb 1st since its allotted on FCFS stay tuned to be active and claim this issue. @Riddhi9570

**Comment by Riddhi9570** [comment]
Okay!👍

**Comment by Riddhi9570** [comment]
I want to work on this issue under JWOC.

**Comment by prathimacode-hub** [comment]
Issue assigned to @Riddhi9570

**Comment by raxvab** [comment]
I want to work on this issue under JWOC

**Comment by prathimacode-hub** [comment]
This issue is already assigned @raxvab

**Comment by raxvab** [comment]
I have commented knowing the fact that if the participant can't complete any task in stipulated time it will be assigned to next one automatically.
Thank you

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by prathimacode-hub** [comment]
This issue is assigned but if it isn't done by earlier assigned person on stipulated time, it would be transferred to next person on queue @codervivek5

**Comment by Riddhi9570** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/72887868/151983555-31c49a9d-c55c-4063-a7eb-8e13b0d8f5a1.png)
@prathimacode-hub Is it fine?

**Comment by prathimacode-hub** [comment]
This is good but we can add more things. In Contact form, add additional input field of Subject. When user fill the details, they should get a instant prompt message like "Your message has been sent, Thank You!!". Along with it, add dummy location, mail id and call details in row format beside contact form. @Riddhi9570
