### ISSUE TITLE
Treksy: Navbar Hamburger not working in mobile view

### ISSUE THREAD

**Issue by Swatilekha-Roy** [prathimacode-hub/Treksy#44]
Please fix the navbar hamburger javascript for all the pages. 

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/Treksy/blob/main/CONTRIBUTING.md) at least once before contributing code to Tresky.

**Comment by Swatilekha-Roy** [comment]
Assigned, @19082002 ! All the best.

**Comment by 19082002** [comment]
> Assigned, @19082002 ! All the best.

Thank you .I try my best.
