### ISSUE TITLE
Treksy : Create Complete Sign Up / Login Details of Website 

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Treksy#5]
Hey JWOC participants, good to see you.

This issue's goal is to create an an overall sign up and login process of the website.

If you like to work on this issue, follow the contributing guidelines provided and have a good read of them along with README file

**Comment by mridul4101** [comment]
I want to work on this issue under JWOC

**Comment by combatantash** [comment]
I want to work on this issue under JWOC

**Comment by prathimacode-hub** [comment]
Issue assigned to @mridul4101

**Comment by Rik-21** [comment]
Can i work on this issue under JWoC

**Comment by prathimacode-hub** [comment]
This is already assigned @Rik-21
