### ISSUE TITLE
Design Logo and Favicon for the website.

### ISSUE THREAD

**Issue by Aniket-508** [prathimacode-hub/Treksy#50]
@prathimacode-hub I want to work on this issue under JWoC.

**Comment by prathimacode-hub** [comment]
Why have you closed this issue? @Aniket-508

**Comment by Aniket-508** [comment]
Since it was already raised by someone else, and work was in the progress already by another assignee.

**Comment by prathimacode-hub** [comment]
I had given time till tomorrow for it to be done. If it isn't I shall assign this to you. Kindly wait for few more hours. @Aniket-508
