### ISSUE TITLE
Treksy : [BUG] About Us Section of website need UI changes

### ISSUE THREAD

**Issue by itshypon** [prathimacode-hub/Treksy#58]
---
Title: About Us Section of website need UI changes
About: About Us section of website contain elements in a messed up positions so changes are necessary to make it look better and arranged
Name: Himanshu
Label: Bug Report
Assignee: ''

---

Define You:

- [x] Hacktoberfest Participant
- [ ] Contributor

Yes

**Describe the Bug**

**Steps to Reproduce**

1.  Go to Treksy website
2. Open About Us Section of website
3. You will the webpage that need changes

**Expected Behavior**

Website should contain elements in an arranged manner to make it user interactive.

This is how it will look like after changes
![image](https://user-images.githubusercontent.com/30335924/193577506-9be93d5c-0633-4bd8-9f04-675465fb4876.png)
![image](https://user-images.githubusercontent.com/30335924/193577607-9f5fe5fa-58b2-4a9c-a192-65abdf1c10df.png)

![image](https://user-images.githubusercontent.com/30335924/193577771-d6930b79-da4c-4cef-a0a4-87cba87f947a.png)

**Comment by prathimacode-hub** [comment]
Issue assigned to @itshypon. You can proceed.

**Comment by prathimacode-hub** [comment]
Can you add the Bug report template here along with the issue description before I merge the PR. @itshypon

**Comment by itshypon** [comment]
@prathimacode-hub done
