### ISSUE TITLE
Treksy : Create a Trip Planner for Website

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Treksy#6]
Hey JWOC participants, good to see you.

This issue's goal is to create a trip planner with complete detailed inputs

If you like to work on this issue, follow the contributing guidelines provided and have a good read of them along with README file

**Comment by ishitaac** [comment]
"I want to work on this issue under JWOC"

**Comment by prathimacode-hub** [comment]
Issue assigned to @ishitaac

**Comment by ishitaac** [comment]
how will the trip planner be made? as a table ? and what different details it should entail

**Comment by prathimacode-hub** [comment]
@ishitaac drop me a message in discord. We can have a discussion on this @ishitaac
