### ISSUE TITLE
Add Favicon to the website

### ISSUE THREAD

**Issue by Laxmankohar** [prathimacode-hub/Treksy#60]
Currently, there is no favicon to the website, I want to add this.
This issue is opened under the hacktoberfest.

**Comment by prathimacode-hub** [comment]
Add issue template along with issue details to get it assigned. @Laxmankohar

**Comment by Laxmankohar** [comment]
|     Title         |     About      |    Name       |    Label         |    Assignee  |
| ------------- | ------------- | ------------- | ------------- | ------------- | 
|Add Favicon to the website|Suggest an idea for this project|Laxman kohar|Feature Request|


Define You:

- [x] Hacktoberfest Participant
- [x] Contributor




**Is your feature request related to a problem? Please describe.**

Yes,it helps users save time by allowing them to identify and browse your website without difficulties.

**Describe the solution you'd like...**

I will add a favicon that is available in assets folder of your code.

**Describe alternatives you've considered?**

NA

**Approach to be followed (optional):**

NA

**Screenshot**

![Screenshot (134)](https://user-images.githubusercontent.com/73365025/194017584-1737ac1b-a55e-4979-9392-974e1ccc729c.png)

**Comment by prathimacode-hub** [comment]
Issue assigned to @Laxmankohar

**Comment by Laxmankohar** [comment]
@prathimacode-hub  can you please check it.
![Screenshot (137)](https://user-images.githubusercontent.com/73365025/194297739-f00c796a-6fd6-47e4-9769-d2850b757ef2.png)
