### ISSUE TITLE
Treksy : Create a formal layout of Booking System

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Treksy#7]
Hey JWOC participants, good to see you.

This issue's goal is to create a formal layout of full end booking system

If you like to work on this issue, follow the contributing guidelines provided and have a good read of them along with README file

**Comment by stubborn-1508** [comment]
I would like to work on this issue.please assign it to me

**Comment by prathimacode-hub** [comment]
Issue assigned to @stubborn-1508

**Comment by prathimacode-hub** [comment]
Update please? You had crossed your deadline neither intimated your progress. @stubborn-1508

**Comment by prathimacode-hub** [comment]
This is not a right thing to do. Keeping hold of issue and removing your assignment without any information. @stubborn-1508

**Comment by Riddhi9570** [comment]
I want to work on this issue under JWOC.

**Comment by prathimacode-hub** [comment]
Issue assigned to @Riddhi9570
